FROM carml/go-mxnet:amd64-gpu-latest
LABEL maintainer="pearson@illinois.edu"

RUN apt-get update && apt-get install -y python-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --user quilt

RUN export MXNET_SRC_ROOT="$FRAMEWORKS_DIR/mxnet"